//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.MaterialStorageAmountChangeHistory = new HashSet<MaterialStorageAmountChangeHistory>();
            this.PriorityChangeHistory = new HashSet<PriorityChangeHistory>();
        }
    
        public int Id { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<System.DateTime> EmployeeBithDate { get; set; }
        public string EmployeePassportID { get; set; }
        public string EmployeeBankAccount { get; set; }
        public string EmployeeDiseas { get; set; }
        public Nullable<bool> EmployeeFamilyState { get; set; }
        public Nullable<int> EmployeeRole { get; set; }
        public Nullable<int> EmployeeWorkplace { get; set; }
    
        public virtual EmployeeRole EmployeeRole1 { get; set; }
        public virtual Workplace Workplace { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStorageAmountChangeHistory> MaterialStorageAmountChangeHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriorityChangeHistory> PriorityChangeHistory { get; set; }
    }
}
