//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialStorageAmountChangeHistory
    {
        public int Id { get; set; }
        public Nullable<int> MaterialName { get; set; }
        public Nullable<decimal> MaterialOldStorageAmount { get; set; }
        public Nullable<decimal> MaterialNewStorageAmount { get; set; }
        public Nullable<decimal> MaterialMinStorageAmount { get; set; }
        public Nullable<int> EmployeeName { get; set; }
        public Nullable<int> OperationType { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Material Material { get; set; }
        public virtual OperationType OperationType1 { get; set; }
    }
}
