//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriorityChangeHistory
    {
        public int Id { get; set; }
        public Nullable<int> Agent { get; set; }
        public Nullable<int> ManagerId { get; set; }
        public string PriorityChangeValue { get; set; }
    
        public virtual Agent Agent1 { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
