//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductProduction
    {
        public int Id { get; set; }
        public Nullable<System.TimeSpan> ProductionTime { get; set; }
        public Nullable<int> Workplace { get; set; }
        public Nullable<int> ProdcutMaterial { get; set; }
        public Nullable<int> ProductionEmployeeAmount { get; set; }
    
        public virtual ProductMaterial ProductMaterial { get; set; }
        public virtual Workplace Workplace1 { get; set; }
    }
}
