//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductMaterial = new HashSet<ProductMaterial>();
            this.ProductMinPriceChangeHistory = new HashSet<ProductMinPriceChangeHistory>();
        }
    
        public int Id { get; set; }
        public string ProductLable { get; set; }
        public Nullable<int> ProductType { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<decimal> ProductMinPrice { get; set; }
        public string ProductSize { get; set; }
        public string ProductSelfWeight { get; set; }
        public string ProductFinalWeight { get; set; }
        public byte[] ProductSertificate { get; set; }
        public Nullable<int> ProductStandart { get; set; }
    
        public virtual ProductType ProductType1 { get; set; }
        public virtual Standart Standart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMaterial> ProductMaterial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductMinPriceChangeHistory> ProductMinPriceChangeHistory { get; set; }
    }
}
