//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype1.model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supplier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Supplier()
        {
            this.MaterialSupplier = new HashSet<MaterialSupplier>();
        }
    
        public int Id { get; set; }
        public string SupplierName { get; set; }
        public Nullable<int> SupplierType { get; set; }
        public string SupplierInn { get; set; }
        public Nullable<int> SupplierQualityRate { get; set; }
        public Nullable<System.DateTime> SupplierStartDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialSupplier> MaterialSupplier { get; set; }
        public virtual SupplierType SupplierType1 { get; set; }
    }
}
